spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://api.sosohandays.com:21001/sosohandays?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul # 실제 운영 DB URL
    username: webapp
    password: 1


logging:
  file:
    name: logs/sosohandays-dev.log
  level:
    root: INFO
    com.sosohandays: DEBUG

    # MyBatis 관련 로그 설정
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG  # 마이바티스 핵심 패키지
    org.mybatis.spring: DEBUG # MyBatis-Spring 연동 패키지

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"