spring:
  config:
    activate:
      on-profile: devD

  datasource:
    url: jdbc:mariadb://api.sosohandays.com:21001/sosohandays?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul # 실제 운영 DB URL
    username: webapp
    password: ssw@#1029
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1

logging:
  file:
    name: logs/sosohandays-dev.log
  level:
    root: DEBUG
    com.sosohandays: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"