spring:
  profiles:
    active: live # 기본적으로 live 프로파일 활성화

  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000


mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sosohandays.metaadmin

jwt:
  access-secret: 04D0H7ebml1yGhVjsLDSDwL64EY5W+uxmBRJxUC83DI=
  access-expiration-ms: 3600000   # 1시간
  refresh-secret: N7KJ7QVTl6oNDrjuJflHjLsJ9uoh12H/ZgIfAyOLrfA=
  refresh-expiration-ms: 604800000 # 7일