spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://api.sosohandays.com:21001/sosohandays?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: webapp
    password: ssw@#1029

logging:
  file:
    name: logs/sosohandays-dev.log
  level:
    root: INFO
    com.sosohandays: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"